// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
public class CourseBrick
{
	public GameObject brick;
	public Vector3 location;

	public CourseBrick( GameObject obj, float x, float z ){
		brick = obj;
		location = new Vector3(x, 0.0f, z);
	}

	public CourseBrick( GameObject obj, float x, float y, float z ){
		brick = obj;
		location = new Vector3(x, y, z);
	}

}

